/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.adtarea06;

import java.util.ArrayList;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author Carlos
 */
public class MiniTwitter extends javax.swing.JFrame {

    /**
     * Creates new form MiniTwittter
     */
    static final int tamanoPagina = 5;//Constante para el tamaño de la pagina, comun a todas las instancias de MiniTwitter
    int numeroPagina = 0;// Pagina en la que se encuentra
    int estadoPanelMensajes = 0;// Que mensajes se están viendo //0 es todos//1 de usuario//
    ModeloTablaSeguidos modeloTablaSeguidos;
    ModeloTablaBuscados modeloTablaBuscados;
    ModeloTablaMensajes modeloTablaMensajes;
    ArrayList<Usuario> seguidos;
    ArrayList<Usuario> buscados;
    ArrayList<Mensaje> mensajes;
    Usuario user;// Usuario en activo en la aplicacion
    Usuario uAux;// Usuario seleccionado para seguir.
    Repositorio rep;
    String cadenaAux;//Para pasar mensajes al repositorio.

    public MiniTwitter() {
        initComponents();
    }

    public MiniTwitter(Usuario user, Repositorio rep) {
        this();
        this.user = user;
        this.rep = rep;
        uAux = null;
        seguidos = rep.getSeguidos(user);
        buscados = new ArrayList();
        mensajes = rep.getMensajes(this);
        System.out.println("size " + mensajes.size());
        for (Mensaje m : mensajes) {

            System.out.println(m.toString());
        }
        modeloTablaMensajes = new ModeloTablaMensajes(mensajes);
        modeloTablaSeguidos = new ModeloTablaSeguidos(seguidos);
        modeloTablaBuscados = new ModeloTablaBuscados(buscados);
        this.tablaUsuariosSeguidos.setModel(modeloTablaSeguidos);
        this.tablaUsuariosBuscados.setModel(modeloTablaBuscados);
        this.tablaMensajes.setModel(modeloTablaMensajes);
        this.setWithColumns(tablaMensajes, new int[]{100, 100, 100, 200});

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonBuscarUsuarios = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        botonSeguirUsuario = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuariosSeguidos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuariosBuscados = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        botonVerAllMensajes = new javax.swing.JButton();
        botonMensajesSeguidos = new javax.swing.JButton();
        botonMensajesPorHashTag = new javax.swing.JButton();
        hashtagtext = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonRetrocederPagina = new javax.swing.JButton();
        BotonAvanzarMensajes = new javax.swing.JButton();
        paginaLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaMensajes = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        botonEnviarMensaje = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoMensajeAEnviar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Siguiendo a:");

        botonBuscarUsuarios.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        botonBuscarUsuarios.setText("Buscar usuarios");
        botonBuscarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarUsuariosActionPerformed(evt);
            }
        });

        botonSeguirUsuario.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        botonSeguirUsuario.setText("Seguir usuario");
        botonSeguirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSeguirUsuarioActionPerformed(evt);
            }
        });

        jScrollPane5.setHorizontalScrollBar(null);

        tablaUsuariosSeguidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuariosSeguidos.setMaximumSize(new java.awt.Dimension(64, 64));
        jScrollPane1.setViewportView(tablaUsuariosSeguidos);

        jScrollPane5.setViewportView(jScrollPane1);

        tablaUsuariosBuscados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaUsuariosBuscados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosBuscadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaUsuariosBuscados);

        jScrollPane6.setViewportView(jScrollPane3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonBuscarUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(botonSeguirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonBuscarUsuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonSeguirUsuario)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        label1.setFont(new java.awt.Font("Comic Sans MS", 3, 48)); // NOI18N
        label1.setText("MINITWITTER");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonVerAllMensajes.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        botonVerAllMensajes.setText("Ver todos");
        botonVerAllMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerAllMensajesActionPerformed(evt);
            }
        });

        botonMensajesSeguidos.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        botonMensajesSeguidos.setText("Seguidos");
        botonMensajesSeguidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMensajesSeguidosActionPerformed(evt);
            }
        });

        botonMensajesPorHashTag.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        botonMensajesPorHashTag.setText("Por Hashtag");
        botonMensajesPorHashTag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMensajesPorHashTagActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setText("MENSAJES");

        botonRetrocederPagina.setText("<<   Retroceder página");
        botonRetrocederPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetrocederPaginaActionPerformed(evt);
            }
        });

        BotonAvanzarMensajes.setText("Avanzar página>>");
        BotonAvanzarMensajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAvanzarMensajesActionPerformed(evt);
            }
        });

        paginaLabel.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        paginaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paginaLabel.setText("0");
        paginaLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tablaMensajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tablaMensajes);

        jScrollPane7.setViewportView(jScrollPane4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(botonRetrocederPagina)
                        .addGap(13, 13, 13)
                        .addComponent(paginaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonAvanzarMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(botonVerAllMensajes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonMensajesSeguidos, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(botonMensajesPorHashTag)
                                .addGap(18, 18, 18)
                                .addComponent(hashtagtext, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVerAllMensajes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMensajesSeguidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMensajesPorHashTag, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hashtagtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonRetrocederPagina)
                    .addComponent(BotonAvanzarMensajes)
                    .addComponent(paginaLabel))
                .addGap(481, 481, 481))
        );

        botonEnviarMensaje.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        botonEnviarMensaje.setText("ENVIAR MENSAJE");
        botonEnviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnviarMensajeActionPerformed(evt);
            }
        });

        textoMensajeAEnviar.setColumns(20);
        textoMensajeAEnviar.setLineWrap(true);
        textoMensajeAEnviar.setRows(5);
        textoMensajeAEnviar.setMargin(new java.awt.Insets(10, 15, 15, 10));
        jScrollPane2.setViewportView(textoMensajeAEnviar);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonEnviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnviarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEnviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnviarMensajeActionPerformed
        // TODO add your handling code here:
        //Creamos un mensaje
        Mensaje msg = new Mensaje();
        msg.setText(this.textoMensajeAEnviar.getText());//Añadimos texto
        User msgUser = new User(this.user.getNome(), this.user.getUsername());//Añadimos el User
        msg.setUser(msgUser);
        //Obtener los Hashtags:
        System.out.println("Matcheando...");
        Pattern patron = Pattern.compile("#\\S+\\s");
        Matcher matcher = patron.matcher(this.textoMensajeAEnviar.getText());
        //Añadir los hashtags al mensaje
        while (matcher.find()) {
            String texto = matcher.group();
            texto = texto.replaceFirst("#", "").trim();//Quitar el # y el espacio en blanco final
            System.out.println(texto);
            msg.getHashtags().add(texto);//Añadimos el hashtag, quitando el #
        }
        //Añadir fecha;
        Date now = new Date();
        msg.setDate(now);
        //Insertar el mensaje.
        this.textoMensajeAEnviar.setText("");
        rep.insertarMensaje(msg);

    }//GEN-LAST:event_botonEnviarMensajeActionPerformed

    private void botonBuscarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarUsuariosActionPerformed
        // TODO add your handling code here:
        ArrayList<Usuario> busqueda;
        String criterio = this.jTextField1.getText();
        this.buscados.clear();
        buscados.addAll(rep.getUsuariosBuscadosPorUsername(criterio));
        this.tablaUsuariosBuscados.revalidate();

        this.tablaUsuariosBuscados.repaint();
    }//GEN-LAST:event_botonBuscarUsuariosActionPerformed

    private void botonMensajesSeguidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMensajesSeguidosActionPerformed
        // TODO add your handling code here:
        this.estadoPanelMensajes = 1;
        flushTablaMensajes();
    }//GEN-LAST:event_botonMensajesSeguidosActionPerformed

    private void BotonAvanzarMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAvanzarMensajesActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        this.numeroPagina++;//avanzamos pagina
        ArrayList<Mensaje> maux = rep.getMensajes(this);// guardamos en un arraylist temporal, por si hemos llegado a final de pagina.
        if (maux.size() == 0) {// Si no hay resultados avanzando pagina, es que nos hemos pasado (no hay mas resultados)
            numeroPagina--;//retrocedemos a la pagina anterior.
            maux = rep.getMensajes(this);//reestablecemos los resultados de la pagina anterior, que era la ultima.
        }
        //Refrescar tabla mensajes.
        this.modeloTablaMensajes.mensajes = maux; 
        this.paginaLabel.setText(numeroPagina + "");
        this.tablaMensajes.repaint();

    }//GEN-LAST:event_BotonAvanzarMensajesActionPerformed

    private void tablaUsuariosBuscadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosBuscadosMouseClicked
        // TODO add your handling code here:
        int row = this.tablaUsuariosBuscados.rowAtPoint(evt.getPoint());
        uAux = this.buscados.get(row);

    }//GEN-LAST:event_tablaUsuariosBuscadosMouseClicked

    private void botonSeguirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeguirUsuarioActionPerformed
        // TODO add your handling code here:
        if (user.getFollows().contains(uAux.getUsername())) {
            JOptionPane.showConfirmDialog(this, "Ya sigue al usuario indicado", "Alerta!", JOptionPane.DEFAULT_OPTION);
        } else {
            user.getFollows().add(uAux.getUsername());
            rep.updateUser(user);
            this.seguidos.add(uAux);
            this.buscados.remove(uAux);
            this.tablaUsuariosSeguidos.revalidate();
            this.tablaUsuariosBuscados.revalidate();
            this.tablaUsuariosSeguidos.repaint();
            this.tablaUsuariosBuscados.repaint();
        }

    }//GEN-LAST:event_botonSeguirUsuarioActionPerformed

    private void botonRetrocederPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetrocederPaginaActionPerformed
        // TODO add your handling code here:
        if (numeroPagina > 0) {
            this.numeroPagina--;//retrocedemos pagina pagina
            this.modeloTablaMensajes.mensajes = rep.getMensajes(this);
            this.paginaLabel.setText(numeroPagina + "");
            this.tablaMensajes.repaint();
        } else {
//            this.modeloTablaMensajes.mensajes = rep.getMensajes(this);
//            this.paginaLabel.setText(numeroPagina + "");
//            this.tablaMensajes.repaint();
        }
        //Repintar
        this.paginaLabel.setText(numeroPagina + "");
        this.tablaMensajes.repaint();

    }//GEN-LAST:event_botonRetrocederPaginaActionPerformed

    private void botonVerAllMensajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerAllMensajesActionPerformed
        this.estadoPanelMensajes = 0;// Vamos a ver todos.
        flushTablaMensajes();
    }//GEN-LAST:event_botonVerAllMensajesActionPerformed


    private void botonMensajesPorHashTagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMensajesPorHashTagActionPerformed
        // TODO add your handling code here:
        this.estadoPanelMensajes = 2;
        cadenaAux = this.hashtagtext.getText();
        flushTablaMensajes();

    }//GEN-LAST:event_botonMensajesPorHashTagActionPerformed
    private void flushTablaMensajes() {
        this.numeroPagina = 0; //Pone la pagina en 
        this.modeloTablaMensajes.mensajes = rep.getMensajes(this);// Cambia los datos de la tabla
        this.tablaMensajes.repaint();//redibuja la tabla.
        this.paginaLabel.setText(""+numeroPagina);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniTwitter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniTwitter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAvanzarMensajes;
    private javax.swing.JButton botonBuscarUsuarios;
    private javax.swing.JButton botonEnviarMensaje;
    private javax.swing.JButton botonMensajesPorHashTag;
    private javax.swing.JButton botonMensajesSeguidos;
    private javax.swing.JButton botonRetrocederPagina;
    private javax.swing.JButton botonSeguirUsuario;
    private javax.swing.JButton botonVerAllMensajes;
    private javax.swing.JTextField hashtagtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private javax.swing.JLabel paginaLabel;
    private javax.swing.JTable tablaMensajes;
    private javax.swing.JTable tablaUsuariosBuscados;
    private javax.swing.JTable tablaUsuariosSeguidos;
    private javax.swing.JTextArea textoMensajeAEnviar;
    // End of variables declaration//GEN-END:variables

    private void setWithColumns(JTable tabla, int[] columnas) {

        for (int i = 0; i < columnas.length; i++) {
            System.out.println(i + "----");
            TableColumn column = tabla.getColumnModel().getColumn(i); //cogemos la columna que corresponde al indice.
            column.setPreferredWidth(columnas[i]); //aplicamos el valor que corresponde en el array

        }
    }

    public Usuario getUser() {
        return user;
    }

    public void setUser(Usuario user) {
        this.user = user;
    }

}
